### ISSUE TITLE
Enhancement: Find a way to stop double editor creation on startup.

### ISSUE THREAD

**Issue by Teklad** [notepadqq/notepadqq#392]
Currently, when notepadqq is started... we create loadedSession Editors+1...  This became apparent while working with QWebEngine.

Here's the relevant GDB output:
```gdb
(gdb) run
Starting program: /home/justin/Projects/notepadqq/out/debug/lib/notepadqq-bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Start-time benchmark started.
WARNING: Notepadqq is running in DEBUG mode.
[New Thread 0x7fffd85d6700 (LWP 24113)]
[New Thread 0x7fffd5463700 (LWP 24114)]
[Thread 0x7fffd5463700 (LWP 24114) exited]
[New Thread 0x7fffd5463700 (LWP 24115)]

Thread 1 "notepadqq-bin" received signal SIGINT, Interrupt.
0x00007fffeeda5f5f in raise () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fffeeda5f5f in raise () from /usr/lib/libpthread.so.0
#1  0x000000000047bb66 in EditorNS::Editor::Editor (this=0xd50e30, parent=0x0)
    at EditorNS/editor.cpp:26
#2  0x000000000047c80f in EditorNS::Editor::addEditorToBuffer (howMany=1)
    at EditorNS/editor.cpp:132
#3  0x0000000000427284 in main (argc=1, argv=0x7fffffffe868) at main.cpp:106
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) n
Program not restarted.
(gdb) continue
Continuing.
EditorNS::Editor(0xd50e30)
[New Thread 0x7fffcffff700 (LWP 24116)]
[New Thread 0x7fffcf7fe700 (LWP 24118)]
[New Thread 0x7fffceffd700 (LWP 24119)]
[New Thread 0x7fffce7fc700 (LWP 24120)]
[New Thread 0x7fffcddee700 (LWP 24121)]
[New Thread 0x7fffcd5ed700 (LWP 24122)]
[New Thread 0x7fffccdec700 (LWP 24123)]
[New Thread 0x7fffb3fff700 (LWP 24124)]
[New Thread 0x7fffb37fe700 (LWP 24125)]
[New Thread 0x7fffb2ffd700 (LWP 24126)]
[New Thread 0x7fffb27fc700 (LWP 24127)]
[New Thread 0x7fffb1ffb700 (LWP 24128)]
[New Thread 0x7fffb17fa700 (LWP 24129)]
[New Thread 0x7fffb0ff9700 (LWP 24130)]
[New Thread 0x7fff8ffff700 (LWP 24131)]
[New Thread 0x7fff8f7fe700 (LWP 24132)]
[New Thread 0x7fff8effd700 (LWP 24133)]
[New Thread 0x7fff8e7fc700 (LWP 24134)]
[New Thread 0x7fff8d7fa700 (LWP 24135)]
[New Thread 0x7fff8dffb700 (LWP 24136)]
[New Thread 0x7fff8cff9700 (LWP 24137)]
Extension support is not installed.

Thread 1 "notepadqq-bin" received signal SIGINT, Interrupt.
0x00007fffeeda5f5f in raise () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007fffeeda5f5f in raise () from /usr/lib/libpthread.so.0
#1  0x000000000047bb66 in EditorNS::Editor::Editor (this=0xf25f60, parent=0x0)
    at EditorNS/editor.cpp:26
#2  0x000000000047c732 in EditorNS::Editor::getNewEditorUnmanagedPtr (
    parent=0xe304b0) at EditorNS/editor.cpp:119
#3  0x000000000047c660 in EditorNS::Editor::getNewEditor (parent=0xe304b0)
    at EditorNS/editor.cpp:109
#4  0x0000000000462259 in EditorTabWidget::rawAddEditorTab (this=0xe304b0, 
    setFocus=true, title=..., source=0x0, sourceTabIndex=0)
    at editortabwidget.cpp:100
#5  0x0000000000461dd8 in EditorTabWidget::addEditorTab (this=0xe304b0, 
    setFocus=true, title=...) at editortabwidget.cpp:40
#6  0x000000000046598c in DocEngine::addNewDocument (this=0xea7a80, name=..., 
    setFocus=true, tabWidget=0xe304b0) at docengine.cpp:26
#7  0x000000000042e1e8 in MainWindow::on_action_New_triggered (this=0xe2a0e0)
    at mainwindow.cpp:636
#8  0x00000000004c34e8 in MainWindow::qt_static_metacall (_o=0xe2a0e0, 
    _c=QMetaObject::InvokeMetaMethod, _id=8, _a=0x7fffffffdf10)
    at ../../out/build_data/moc_mainwindow.cpp:546
#9  0x00000000004c43d4 in MainWindow::qt_metacall (this=0xe2a0e0, 
    _c=QMetaObject::InvokeMetaMethod, _id=8, _a=0x7fffffffdf10)
    at ../../out/build_data/moc_mainwindow.cpp:795
#10 0x00007fffef4ddee4 in QMetaObject::activate(QObject*, int, int, void**) ()
```

It would be great if we could find a way to remove the double instancing... as it would improve startup performance just a bit.

**Comment by danieleds** [comment]
That's because of the Editor buffer. It's expected and it's what allows to have fast tab creation.
