### ISSUE TITLE
Crash after pasting and entering text

### ISSUE THREAD

**Issue by andres101** [notepadqq/notepadqq#539]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Entering specific text causes a crash
**Expected behavior**

Expected the text: c.remove_itemcontainer
**Minimal reproduction of the problem with instructions**

Open a new tab
Paste the following text: remove_itemcontainer
Press the "Home" key
Type: c.
**Please tell us about your environment:**

Ubunbtu 17.10, Qt 5.9.1, Notepadqq v1.2.0

**Comment by noabody** [comment]
Same environment.  GDB backtrace on source build with debugging symbols.
Trying to make any edit within this text causes SIGSEGV
```
[HKEY_LOCAL_MACHINE\Software\Ubisoft\Beyond Good & Evil]
```
```
Starting program: /notepadqq/out/debug/lib/notepadqq-bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Start-time benchmark started.
WARNING: Notepadqq is running in DEBUG mode.
[New Thread 0x7fffe3969700 (LWP 12703)]
[New Thread 0x7fffd8708700 (LWP 12704)]
[New Thread 0x7fffd7f07700 (LWP 12705)]
[New Thread 0x7fffd7706700 (LWP 12706)]
[New Thread 0x7fffd6426700 (LWP 12707)]
[New Thread 0x7fffd5c25700 (LWP 12708)]
[New Thread 0x7fffd5405700 (LWP 12709)]
[New Thread 0x7fffd4c04700 (LWP 12710)]
[New Thread 0x7fff87ffd700 (LWP 12711)]
[New Thread 0x7fff873fc700 (LWP 12712)]
[New Thread 0x7fff6e795700 (LWP 12714)]
[New Thread 0x7fff6df94700 (LWP 12715)]
[New Thread 0x7fff6d76f700 (LWP 12716)]
[New Thread 0x7fff6cf4a700 (LWP 12717)]
[New Thread 0x7fff5fa29700 (LWP 12718)]
[New Thread 0x7fff5f17b700 (LWP 12719)]
[Thread 0x7fff5f17b700 (LWP 12719) exited]
[Thread 0x7fff6d76f700 (LWP 12716) exited]
[Thread 0x7fff6cf4a700 (LWP 12717) exited]
[Thread 0x7fff6e795700 (LWP 12714) exited]
[New Thread 0x7fff6e795700 (LWP 12732)]
[Thread 0x7fff6e795700 (LWP 12732) exited]
[New Thread 0x7fff6e795700 (LWP 12733)]
[Thread 0x7fff6e795700 (LWP 12733) exited]
[New Thread 0x7fff6e795700 (LWP 12734)]
[Thread 0x7fff6e795700 (LWP 12734) exited]

Thread 1 "notepadqq-bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff65d0e07 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
(gdb) backtrace
#0  0x00007ffff65d0e07 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#1  0x00007ffff65d1d6b in JSC::JSRopeString::resolveRope(JSC::ExecState*) const () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#2  0x00007ffff66104a0 in  () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#3  0x00007fff87fff0e5 in  ()
#4  0xffff000000000002 in  ()
#5  0x00007ffff64ad87a in  () at /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5
#6  0x0000000000000000 in  ()
```

**Comment by JuBan1** [comment]
Afaik this is a bug/regression in Ubuntu's QtWebKit implementation. Since WK is deprecated I don't know if they'll actually fix it.

Hopefully Nqq will soon replace WK with something faster and more stable (I'm working on it). In the meantime you can use the AppImage version if you want. It should be running fine since it brings along its own version of WK.

**Comment by andres101** [comment]
Thank you for the feedback
