### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by qcerasmus** [notepadqq/notepadqq#695]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```
We're currently experiencing extensions being installed correctly, but not showing up in the menu.
This is the linked ticket: https://github.com/qcerasmus/notepadqq-extensions/issues/1

I honestly can't replicate this. I've tried on Ubuntu and Linux Mint.

**Comment by sharpensteel** [comment]
Hi, bug is reproducing on my PC

Are new extensions should appear in `~/.config/Notepadqq`?
my configuration: Notepadqq v1.4.2, ubuntu 18, nodejs v.10

**Comment by JuBan1** [comment]
New extensions should show up in `~./config/Notepadqq/extensions` but I think there are some things in `usr/share/notepadqq/extension_tools` as well. Perhaps it's a permissions issue with the latter one?

**Comment by Cris70** [comment]
Hi @JuBan1, my problem is an "unsupported runtime" error. I do have the extensions in ~/.config/Notepadqq/extensions though.
Here is my node version:
```
cris@PolariSuse [~]$ node --version
v8.11.2
```
Attached you will find a small video with the problem.
Thank you in advance.
Cris
![peek 2018-06-04 15-52](https://user-images.githubusercontent.com/5107224/40921587-1c47d2ee-6810-11e8-8d7b-10e6106b7d5a.gif)

**Comment by JuBan1** [comment]
Can you try removing the extension from  ~/.config/Notepadqq/extensions and see whether the same error message shows up when trying to install it? As far as I can see, you can *either* get the unsupported runtime error *or* the extension shows up in that folder. Both would be very weird.

Either way, this smells like something inside our JS code not doing what it ought to.

**Comment by Cris70** [comment]
@JuBan1 you're right, I think the extensions were there because in an earlier Notepadqq release I had tried unpacking them there to see if they worked.
I have now cleaned the ~/.config/Notepadqq/extensions directory and tried reinstalling the extensions. I still get the same error message, but nothing gets installed in that directory.

**Comment by JuBan1** [comment]
That's in line with how it looks. I think I might have an idea what's going on. Could you try the following 

1) Run Notepadqq from commandline and try to install the extension. Does the console output any error messages?

2) Run the following command:
`node /usr/local/share/notepadqq/extension_tools/readmanifest.js /path/to/extension.nqqext`.

The `/usr/local/share/notepadqq/extension_tools/` is where the JS scripts used by Nqq to load extensions should be located. The location may vary depending on distro or means of installation, but this is generally the right path.

`readmanifest` output the extension's manifest file as text. The only way I can see how you could get the unsupported runtime error is if this call fails. Perhaps Node outputs warnings (or nothing at all) which messes up the reading of the manifest string.

It looks like nobody ever finished writing the error handling code for extensions. :-1:

**Comment by Cris70** [comment]
OK, so here is what I got when trying the first point:
```
cris@PolariSuse [~]$ notepadqq
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
kf5.kio.core: We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nLoaded services file OK.\nERROR: Invalid idmap range for domain *!\n\n"
""
"illegal value"
```
The first two lines appear as soon as I launch notepadqq. Then, after a few seconds (but apparently not realted to something I do) the third line appears.
Then, as soon as I select an extension file (i.e. **before** clicking on install) I get the last line. I think this is the reason why the extension shows "unknown version, unknown author".
Finally, nothing is shown when I finally click on "Install" and get the error in the GUI.

**Comment by Cris70** [comment]
And here is what I get when I try the second point:

```
cris@PolariSuse [~]$ node /usr/share/notepadqq/extension_tools/readmanifest.js ~/Downloads/done/Hex2Ascii-0.0.1.nqqext
/usr/share/notepadqq/extension_tools/node_modules/adm-zip/adm-zip.js:2
var fs = Utils.FileSystem.require(),
                          ^

TypeError: Cannot read property 'require' of undefined
    at Object.<anonymous> (/usr/share/notepadqq/extension_tools/node_modules/adm-zip/adm-zip.js:2:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/notepadqq/extension_tools/readmanifest.js:1:76)
    at Module._compile (module.js:652:30)
```

**Comment by JuBan1** [comment]
I see! It's an issue with Notepadqq 1.4.0 through 1.4.2.

According to the git history, the adm-zip package was updated, but that was reverted later because it broke extensions. The revert came shortly after the 1.4.2 release.

The most direct way of fixing this would be to move to 1.4.4+. Alternatively you could replace the adm-zip folder on your system with the one found [here](https://github.com/notepadqq/notepadqq/tree/master/src/extension_tools/node_modules) in out git tree. That's a bit hackish but will work.

Thanks for helping to debug the cause.

**Comment by Cris70** [comment]
Thank you @JuBan1 !!
I usually prefer to wait for the new release to be available through the official repository.
I see that, though version 1.4.8 is available, GitHub still marks v1.4.0 as "Latest release". 
I suspect that openSUSE won't be updating the package until the "Latest release" tag is moved to a newer release.
In the meantime, I'll use the "hackish" work-around ;^)

**Comment by Cris70** [comment]
@JuBan1 I think there is something else.
I have now updated my adm-zip folder with that in the archive of notepadqq v1.4.4. Installation now apparently works fine and files are copied in the ~/.config/Notepadd/extensions directory.
However, I do not see anything in the "Extensions" menu of Notepadqq, even after restarting Notepadqq.

I understand that now my Notepadqq installation is a bit like a patchwork, so my bug report is to be taken with a grain of salt.
However, I get the identical same behavior as reported by  @sharpensteel in [this bug report](https://github.com/qcerasmus/notepadqq-extensions/issues/1), and he claims to have v1.4.2 installed.

**Comment by JuBan1** [comment]
Seems like NodeJS have gotten rid of an old option that Nqq is using. Can you try running `node --harmony-proxy` and see if you get a `bad option` error? If you do, that's the issue.

Bad news is, it's not easily fixed. Unless you want to downgrade NodeJS (which is probably a bad idea) you'd have to use a patched version of Nqq. And I can't commit a patch into master because I don't know what versions of NodeJS are affected, or whether it would break anything. :(

Honestly, Nqq's extension system is on really shaky legs. On the plus side, I've been putting research into a proper rework of the extension system. Though no saying when that's coming.

**Comment by Cris70** [comment]
Here it is @JuBan1:
```
cris@PolariSuse [~]$ node --harmony-proxy
/usr/bin/node-default: bad option: --harmony-proxy
```
Good to know that the extensions system is being worked on.
I hope it will not be a too lengthy process.

Thank you!
Cris

**Comment by JuBan1** [comment]
> p.s. Any hope you will be reconsidering your decision to use javascript as extension language?

Probably not. JS is pretty ubiquous, and built into the Qt framework which makes it a good choice. My current proposal is to stick with JS but get rid of Node/NPM to remove any external dependencies.

**Comment by Cris70** [comment]
> My current proposal is to stick with JS but get rid of Node/NPM to remove any external dependencies.

Fair enough!
Thank you

**Comment by voidray** [comment]
Just a note regarding performance: I checked sublime (python extensions) and vscode (js) regarding formatting of larger xml files (>10.000 lines). Both were much slower than np++ with larger files (sublime even froze). So it is something worth keeping in mind.
